tap "felixkratz/formulae"
tap "nikitabobko/tap"
tap "romkatv/powerlevel10k"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Modern, C++-native, test framework
brew "catch2"
# Cross-platform make
brew "cmake"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# General-purpose data compression with high compression ratio
brew "xz"
# GNU compiler collection
brew "gcc"
# GitHub command-line tool
brew "gh"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Python version management
brew "pyenv"
# Tool Command Language
brew "tcl-tk"
# Sends magic packets to wake up network-devices
brew "wakeonlan"
# A window border system for macOS
brew "felixkratz/formulae/borders"
# Custom macOS statusbar with shell plugin, interaction and graph support
brew "felixkratz/formulae/sketchybar"
# AeroSpace is an i3-like tiling window manager for macOS
cask "aerospace"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-sketchybar-app-font"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Full TeX Live distribution without GUI applications
cask "mactex-no-gui"
# Tool that provides consistent, highly configurable symbols for apps
cask "sf-symbols"
# Open-source code editor
cask "visual-studio-code"
vscode "arrrrny.zed-one-theme"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.code-runner"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "james-yu.latex-workshop"
vscode "jamesmaj.easy-icons"
vscode "mechatroner.rainbow-csv"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "openai.chatgpt"
vscode "patricknasralla.tokyo-night-moon"
vscode "pkief.material-icon-theme"
vscode "qwtel.sqlite-viewer"
vscode "ritwickdey.liveserver"
vscode "zhuangtongfa.material-theme"
vscode "zhuangtongfa.one-dark-pro"
