tap "felixkratz/formulae"
tap "jandedobbeleer/oh-my-posh"
tap "nikitabobko/tap"
tap "romkatv/powerlevel10k"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# General-purpose data compression with high compression ratio
brew "xz"
# Python code formatter
brew "black"
# Modern, C++-native, test framework
brew "catch2"
# Cross-platform make
brew "cmake"
# Generate documentation for several programming languages
brew "doxygen"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Graph visualization software from AT&T and Bell Labs
brew "graphviz"
# Sort Python imports automatically
brew "isort"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Powerful, lightweight programming language
brew "lua"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Create, run, and share large language models (LLMs)
brew "ollama", restart_service: :changed
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Extremely fast Python linter, written in Rust
brew "ruff"
# Tool Command Language
brew "tcl-tk"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Parser generator tool
brew "tree-sitter-cli"
# Markup-based typesetting system
brew "typst"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Command-line interface to the WakaTime api
brew "wakatime-cli"
# Sends magic packets to wake up network-devices
brew "wakeonlan"
# General-purpose lossless data-compression library
brew "zlib"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# A window border system for macOS
brew "felixkratz/formulae/borders"
# Custom macOS statusbar with shell plugin, interaction and graph support
brew "felixkratz/formulae/sketchybar"
# Prompt theme engine for any shell
brew "jandedobbeleer/oh-my-posh/oh-my-posh"
# AeroSpace is an i3-like tiling window manager for macOS
cask "nikitabobko/tap/aerospace"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# Preference Pane for controlling cursor hiding
cask "cursorcerer"
# App to build and share containerised applications and microservices
cask "docker-desktop"
# Web browser
cask "firefox"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-sf-pro"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Customise mouse behavior
cask "linearmouse"
# Privacy-first, open-source platform for knowledge sharing and management
cask "logseq"
# Full TeX Live distribution without GUI applications
cask "mactex-no-gui"
# Control your tools with a few keystrokes
cask "raycast"
# Tool that provides consistent, highly configurable symbols for apps
cask "sf-symbols"
# App that enables mouse-free UI interaction
cask "shortcat"
# PDF reader and note-taking application
cask "skim"
# Binary releases of VS Code without MS branding/telemetry/licensing
cask "vscodium"
vscode "enkia.tokyo-night"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.code-runner"
vscode "james-yu.latex-workshop"
vscode "joshmu.periscope"
vscode "mathematic.vscode-latex"
vscode "mechatroner.rainbow-csv"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools-themes"
vscode "myriad-dreamin.tinymist"
vscode "pkief.material-icon-theme"
vscode "pkief.material-product-icons"
vscode "qwtel.sqlite-viewer"
vscode "ritwickdey.liveserver"
vscode "ryuta46.multi-command"
vscode "subframe7536.custom-ui-style"
vscode "tombi-toml.tombi"
vscode "tomoki1207.pdf"
vscode "vscodevim.vim"
vscode "wakatime.vscode-wakatime"
