{ lib, ... }:

let
  secretsFile = ../../secrets/secrets.yaml;
  # `secrets/secrets.yaml` doesn't exist until sops has been bootstrapped on
  # this machine (see README → "Secrets (sops-nix)"). Gating on
  # pathExists means a fresh clone of this repo evaluates and switches
  # cleanly with the mail feature simply inactive, instead of Nix refusing
  # to build the entire system over one missing encrypted file. Once you
  # create that file, this flips on automatically — no flag to remember.
  secretsBootstrapped = builtins.pathExists secretsFile;
in
{
  sops = lib.mkIf secretsBootstrapped {
    defaultSopsFile = secretsFile;

    # sops-nix's darwin default is already
    # "$HOME/Library/Application Support/sops/age/keys.txt" — spelled out
    # here so it's obvious where the private key has to live on each
    # machine. This file is never generated by Nix; see the README.
    age.keyFile = "/Users/leopoldsprenger/Library/Application Support/sops/age/keys.txt";

    secrets."mail/imap_password" = {
      owner = "leopoldsprenger";
    };
  };
}
